name: dbpp
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bash>=4.4
  - python=3.10
  - perl>=5.26
  - snp-sites=2.5.1
  - newick_utils=1.6
  - git
  - make
  - cxx-compiler
  - zlib
  - wget
  - tar
  - pip
